### ISSUE TITLE
Awkward unerline placing for unnecessary curly brace in string template

### ISSUE THREAD

**Issue by Vampire** [nbadal/ktlint-intellij-plugin#308]
If you have this code
```kts
if (string.isNotBlank()) {
    if (!discordRegex(code).containsMatchIn(string)) {
        string += ("\nhttps://discord.gg/${code}")
    }
}
```
the plugin highlights it as
![image](https://user-images.githubusercontent.com/325196/235882542-1c383c35-4552-4062-bfc1-9a5c394023d2.png)
which seems a bit misplaced.

**Comment by nbadal** [comment]
Interesting! I know my code to infer the placement of the annotation is a bit janky, so I can revisit this example to see if there's a way to clean it up. Ideally, ktlint would return a range of characters that the error affects, but I believe when I implemented this it only included a single character location so I have to guess a little bit about which symbols are included.

**Comment by paul-dingemans** [comment]
This specific problem won't occur anymore in the upcoming release. In that release the plugin enforces that ktlint formatting is applied always on each save or whenever format is invoked. Users should not be bothered by manually fixing errros that can be autocorrected like in this example. A similar problem however can still occur on other errors that can not be autocorrected. Ktlint still only returns the offset to a single position at which the problem occurs.

**Comment by Vampire** [comment]
Ok, thanks, then I will anyway immediately uninstall the plugin and recommend everybody to remove it from their IDE. That behavior is way too aggressive except if I opted in. I often have projects open where for example no trailing commas are used, which imho is good, and where also no ktlint is used anywhere. The IntelliJ plugin nevertheless shows errors for that, as it just always is active if not disabled manually or an `.editorconfig` added which tells ktlint to behave properly.

As long as it only showed an error, I could accept that. But if it now starts to auto correct theses errors and thus auto-uglifies any project I contribute to, or any project someone contributing to me that uses the plugin, that is imho unacceptable behavior.

Even if I invoke the IntelliJ formatter I don't necessarily want ktlint to interfere, as I might like IntelliJ result better.

**Comment by Vampire** [comment]
@paul-dingemans with the changes of #356, will this issue then be relevant again?

**Comment by paul-dingemans** [comment]
I don't know but I have no reason to expect it to happen. But if you find specific occurrences, please report an issue for it.

**Comment by Vampire** [comment]
It is indeed better now, looks like:
![image](https://github.com/nbadal/ktlint-intellij-plugin/assets/325196/d41d1ab7-dd7a-4916-8097-79d3da146938)
It might just be a topic whether the curly braces it complains about should be underlined too and not only the content.
